# -----------------------------------------------------------
# Автоматизации управления гитом
# -----------------------------------------------------------

- alias: "001_push_github"
  trigger:
    - platform: time
      at: 02:00:00
  condition: []
  action:
    - service: shell_command.pushupdates_to_github
      data: {}
  mode: single