
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation ui: !include automations.yaml
script: !include includes/script.yaml
scene: !include scenes.yaml


recorder: !include includes/recorder.yaml
sensor: !include_dir_merge_list includes/sensors
automation manual: !include_dir_merge_list includes/automation
binary_sensor: !include_dir_merge_list includes/binsensors

lovelace:
  mode: yaml
  resources:  
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
